version: '3'
services:
# postres container
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_PASSWORD=postgres_password
# redis container  
  redis:
    image: 'redis:latest'
    # API container
#nginx container
  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile.dev
      context: ./nginx
    ports:
      - '3050:80'
  api:
    build:
      dockerfile: Dockerfile.dev
      context: ./server
    volumes:
      - /usr/app/node_modules
      - ./server:/app
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PGUSER=postgres
      - PGHOST=postgres
      - PGDATABASE=postgres
      - POSTGRES_PASSWORD=postgres_password
      - PGPORT=5432
# React container
  client:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
    - /usr/app/node_modules
    - ./client:/usr/app
  worker:
    build:
      dockerfile: Dockerfile.dev
      context: ./client
    volumes:
    - /usr/app/node_modules
    - ./client:/usr/app
